milvus-io/milvus-proto

proto/common.proto
proto/milvus.proto
proto/schema.proto

Add latest proto from Milvus project.
/cc @yhmo 
Signed-off-by: Congqi Xia <congqi.xia@zilliz.com>

Add current proto file from milvus project

---

proto/common.proto
proto/milvus.proto
proto/schema.proto

Minor change for import interface

---

proto/common.proto
proto/milvus.proto
proto/schema.proto

Update proto files

---

proto/common.proto
proto/milvus.proto

Signed-off-by: Yuchen Gao <yuchen.gao@zilliz.com>

Update proto to the latest version

---

proto/common.proto
proto/milvus.proto

Update proto for bulkload minor change

---

OWNERS

Signed-off-by: Jenny Li <jing.li@zilliz.com>
fix #5

[skip e2e] Update OWNERS file

---

proto/milvus.proto

Signed-off-by: yah01 <yang.cen@zilliz.com>

Add node_ids field for QuerySegmentInfo

---

.github/mergify.yml
.github/workflows/check.yaml

Signed-off-by: Jenny Li <jing.li@zilliz.com>
fix #20

Add test for milvus-proto

---

proto/common.proto
proto/milvus.proto

Update for role access api

---

proto/milvus.proto

Signed-off-by: Yuchen Gao <yuchen.gao@zilliz.com>

Update Proto file

---

proto/common.proto
proto/milvus.proto

Minor change for ShowCollection

---

proto/common.proto
proto/milvus.proto

#29
Signed-off-by: SimFG <bang.fu@zilliz.com>

Update the proto files for the rbac function

---

proto/common.proto
proto/milvus.proto

fix #30 
Signed-off-by: zhenshan.cao <zhenshan.cao@zilliz.com>

Add consistency_level field to proto

---

proto/common.proto
proto/milvus.proto

fix #32 
Signed-off-by: zhenshan.cao <zhenshan.cao@zilliz.com>

Modify response of DescribeCollection and add DescribePartition

---

proto/milvus.proto

fix #35 
Signed-off-by: zhenshan.cao <zhenshan.cao@zilliz.com>

Sync proto from milvus: add GetStatisticsRequest experimental interface

---

proto/milvus.proto

Signed-off-by: yangxuan <xuan.yang@zilliz.com>

And query params to query request

---

proto/common.proto

Signed-off-by: bigsheeper <yihao.dai@zilliz.com>
issue: #38

Add ForceDeny and RateLimit error code

---

proto/common.proto
proto/milvus.proto
proto/schema.proto

Signed-off-by: yhmo <yihua.mo@zilliz.com>
#40

Update to milvus master branch on Step.27

---

proto/common.proto
proto/milvus.proto

Signed-off-by: yhmo <yihua.mo@zilliz.com>
#40

Fix a mistake of pr39

---

proto/common.proto
proto/milvus.proto

related: #44 
See:https://github.com/milvus-io/milvus/pull/19594
Signed-off-by: wayblink <anyang.wang@zilliz.com>

Add GetComponentStates interface

---

proto/milvus.proto

Signed-off-by: SimFG <bang.fu@zilliz.com>

Use underscores to separate parameter names in the GetLoadingProgressRequest

---

proto/google/protobuf/descriptor.proto

Signed-off-by: Enwei Jiao <enwei.jiao@zilliz.com>
issue: https://github.com/milvus-io/milvus/issues/20819

Add google/protobuf/descriptor.proto

---

proto/common.proto
proto/milvus.proto
proto/schema.proto

add csharp_namespace option for csharp sdk.
#57

add csharp_namespace option

---

proto/milvus.proto

Signed-off-by: Yuchen Gao <yuchen.gao@zilliz.com>
https://github.com/milvus-io/milvus-proto/issues/59

Add compaction plan count field to ManualCompactionResponse

---

Makefile
go-api/milvuspb/milvus.pb.go
go-api/schemapb/schema.pb.go

Signed-off-by: SimFG <bang.fu@zilliz.com>

Change the `protoc-gen-go` version to `1.3.2`

---

README.md

add csharp sdk doc

---

.github/mergify.yml

Signed-off-by: Bennu-Li <yunmei.li@zilliz.com>

Add ci fot branch 2.2

---

.github/workflows/check.yaml

Signed-off-by: Bennu-Li <yunmei.li@zilliz.com>

Add ut for branch 2.2

---

proto/common.proto
proto/milvus.proto
proto/schema.proto

Cherry-pick: add  option csharp_namespace (#56)

---

proto/schema.proto

Support dynamic schema

---

proto/common.proto
proto/milvus.proto
proto/schema.proto

[cherry-pick] Change C# namespace to Milvus.Client (#183)

---

proto/milvus.proto

related: https://github.com/milvus-io/milvus/issues/26820

Revert deprecat segmentIDs in GetFlushState

---

go-api/hook/hook.go

Add VerifyAPIKey method for the hook interface

---

proto/schema.proto

add groupby value field(#215)

---

go-api/commonpb/common.pb.go
proto/common.proto

after we updated the schema in #246, we forgot to update the comment here.

update comment of PlaceholderValue::values

---

go-api/hook/hook.go

issue: https://github.com/milvus-io/milvus/issues/30436

Add the return value for the hook report interface

---

proto/milvus.proto

enhance: add privilege for AlterAlias

---

proto/milvus.proto

enhance: add privilege for AlterAlias (#252)

---

.github/mergify.yml
.github/workflows/check.yaml

enhancement: enable 2.4 pipeline

---

proto/common.proto
proto/milvus.proto

enhance: Add AlterDatabase proto

---

proto/milvus.proto

enhance: Add rbac support on describe database api

---

proto/milvus.proto

use the GetLoadState privilege in the GetLoadState and GetLoadingProgress Request

---

proto/milvus.proto

[2.4]: use the GetLoadState privilege in the GetLoadState and GetLoadingProgress Request

---

.github/workflows/check.yaml

Cherry-pick from master
pr: #282 
Use regexp to match all release branches so that all PRs for release branches can have `ci-passed` automatically.

enhance: [2.4] Make proto check action works for all release branches (#282)

---

proto/common.proto

issue: https://github.com/milvus-io/milvus/issues/37031

enhance: RBAC built in privilege groups

---

go-api/hook/hook.go

relate: https://github.com/milvus-io/milvus-proto/issues/370

support push info to hook

---

go-api/hook/hook.go

relate: https://github.com/milvus-io/milvus-proto/issues/370

[Cherry-pick]Support push info to hook (#369)

---

go-api/hook/hook.go

See also: https://github.com/milvus-io/milvus/issues/40013

feature: Add CipherPlugin Interfaces

---

go-api/hook/hook.go

See also: milvus-io/milvus#40013

feat: CMEK add collection id in APIs

---

proto/milvus.proto

issue: https://github.com/milvus-io/milvus-proto/issues/442

Add delete_keys in AlterCollectionFieldRequest

---

proto/milvus.proto

issue: #452 
support row level security related api definition

OpenAPI for Row level security

---

go-api/schemapb/schema.pb.go
proto/schema.proto

Fix uppercase and lowercase and align with master
